### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by jpopelka** [spranesh/Redhawk#1]
any plans to port to Python 3 ?

I for example see:

```
python3 -c 'import redhawk.common.selector'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/redhawk/common/selector.py", line 75, in <module>
    import _selector
ImportError: No module named '_selector'
```

**Comment by ncoghlan** [comment]
I started work on an initial PR for Python 2/3 compatibility at https://github.com/ncoghlan/Redhawk/commit/e924aec8add4015f7c2a614aeb463d8563171692

The major changes in the initial patch are:
- switching to explicit relative imports
- using print as a function rather than as a statement
- using the "exception as name" except clause syntax rather than "exception, name"
- wrapping various builtins with "list" calls to preserve the Py2 behaviour of producing a list
- using six.moves to cope with some standard library rearrangements

The modified implementation mostly passes "python setup.py test" under Python 3.4, but I haven't checked it for Python 2.6/7 compatibility yet. There are also a couple of test failures: test_c_declarations and test_c_expressions both fail to locate their "test_descriptions" file (and switching those lines to use `os.path.join` didn't make a difference).

**Comment by spranesh** [comment]
Wow, thanks, @ncoghlan! I had a preliminary peek and it looks good - I'd be happy to review and upstream it when you are done. Let me know if anything seems particularly hard or unwieldy - I'd be happy to help.

**Comment by spranesh** [comment]
@jpopelka: Thank you for filing an issue. Just to clarify, when you say port do you mean:
1. Redhawk parses and queries python3 codebases.
2. Or Redhawk source code should be python3 compatible?

@ncoghlan's change should address the latter, but not the former.

Right now, I don't have the bandwidth to work on adding Python3 support in the LAST. I suspect I can get around to this over the next quarter, but I cannot make a firm guarantee at this time.

I can provide pointers if that'd help. I'd be happy to review and accept patches!

**Comment by ncoghlan** [comment]
This issue is specifically about getting Redhawk itself running on Python 3 (Jiri & I are working on the same project, and we're interested in running that on 3.4 or 3.5 instead of 2.7)

I filed #2 to cover eventually supporting the new syntactic constructs introduced in 3.3 and 3.5, but most of the code bases we're interested in analysing won't be using those new constructs yet.

**Comment by spranesh** [comment]
Thanks for clarifying and triaging!

**Comment by bkabrda** [comment]
Hi, so I pushed several commits to @ncoghlan's py3-compat branch. All the tests that pass for me on Python 2 now also pass on Python 3; there are however 31 tests (out of 234) that fail on both versions. I'm quite sure that the failures are the same in Python 2 and 3, so it seems I didn't break anything. Nick, feel free to review my commits and create a PR if you think this is good enough. @spranesh, feel free to review any time, I'd be glad for any comments/suggestions.

**Comment by ncoghlan** [comment]
PR submitted: https://github.com/spranesh/Redhawk/pull/3

@bkabrda GitHub was clever enough to migrate my and @jpopelka's comments on the initial python-modernize output from the fork, so you may want to look into those.

**Comment by bkabrda** [comment]
Thanks. I had a look and pushed one more commit that addresses the issues. The PR is ready to be reviewed by @spranesh

**Comment by bkabrda** [comment]
@spranesh sorry to bother you again, but could you please release a new Redhawk version on PyPI? It'd really help me. Now I need to install things from git by pip if I want Python 3 support which is not very nice - I would like to be able to install from PyPI with Python 3 support. Thanks!

**Comment by bkabrda** [comment]
@spranesh ping, any plans for releasing new version of Redhawk with Py3 support?

**Comment by spranesh** [comment]
Yes, I plan to do a release with your changes within the next week or two.

**Comment by jpopelka** [comment]
Hello @spranesh 
It's been few weeks and we'd like to know what's your realistic estimation of the release date. Don't feel pressed -  we just want to finish the porting of our project to Python 3 and need to decide whether to still wait for the release or start running redhawk from the repository. Thank you !

**Comment by spranesh** [comment]
Sorry for dropping the ball on this. Please expect a release by August 23rd (i.e, two weeks from now).

**Comment by ncoghlan** [comment]
Not a problem! Thanks for setting a target date, though - while we've always had the option of installing https://github.com/spranesh/Redhawk/commit/68a7400d73ad730e908435c8ead31d2c914a32a1 directly from version control, we do consider it preferable to run on officially released versions of dependencies :)

**Comment by ncoghlan** [comment]
The 1.2.3 release now includes experimental support for running on Python 3.

However, as noted in #2, additional work will be needed to analyse new Python 3 specific syntax, and @bkabrda indicated in https://github.com/spranesh/Redhawk/pull/3#issuecomment-213305749 that there can be problems with analysing Python 2 only syntax when running on Python 3.
